/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sangueamigo;

import sangueamigo.ConexaoDB;
import sangueamigo.exameDAO;
import sangueamigo.AgendarExames;

/**
 *
 * @author DreEm
 */
public class UsuarioExame extends javax.swing.JFrame {
    AgendarExames exame = new AgendarExames();
                ConexaoDB conn = new ConexaoDB();  
                //doacoesDAO = usuario padrao = todos os métodos de CRUD ficam aqui, tudo do banco fica nele
                //doacao = normal, só os getters e setters
                exameDAO exameBD;
    /**
     * Creates new form ExamesUsuario
     */
    public UsuarioExame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField7 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jQuadroExames = new javax.swing.JPanel();
        lblLocalEx = new javax.swing.JLabel();
        lblDataEx = new javax.swing.JLabel();
        lblHoraEx = new javax.swing.JLabel();
        lblOpcaoEx = new javax.swing.JLabel();
        B5 = new javax.swing.JButton();
        lblTituloEx = new javax.swing.JLabel();
        tx8 = new javax.swing.JTextField();
        tx9 = new javax.swing.JTextField();
        tx11 = new javax.swing.JTextField();
        tx10 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jTextField7.setBackground(new java.awt.Color(204, 0, 0));
        jTextField7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel4.setText("Agendar Doações");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jQuadroExames.setBackground(new java.awt.Color(204, 0, 0));

        lblLocalEx.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblLocalEx.setText("Local:");

        lblDataEx.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblDataEx.setText("Data:");

        lblHoraEx.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblHoraEx.setText("Hora:");

        lblOpcaoEx.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblOpcaoEx.setText("Especialidade:");

        B5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        B5.setText("Agendar");
        B5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5ActionPerformed(evt);
            }
        });

        lblTituloEx.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lblTituloEx.setText("Agendar Exames");

        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jQuadroExamesLayout = new javax.swing.GroupLayout(jQuadroExames);
        jQuadroExames.setLayout(jQuadroExamesLayout);
        jQuadroExamesLayout.setHorizontalGroup(
            jQuadroExamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jQuadroExamesLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(B5, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
            .addGroup(jQuadroExamesLayout.createSequentialGroup()
                .addGroup(jQuadroExamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jQuadroExamesLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jQuadroExamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jQuadroExamesLayout.createSequentialGroup()
                                .addComponent(lblLocalEx)
                                .addGap(18, 18, 18)
                                .addComponent(tx8, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jQuadroExamesLayout.createSequentialGroup()
                                .addComponent(lblDataEx)
                                .addGap(18, 18, 18)
                                .addComponent(tx9, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblTituloEx)
                            .addGroup(jQuadroExamesLayout.createSequentialGroup()
                                .addComponent(lblHoraEx)
                                .addGap(18, 18, 18)
                                .addComponent(tx10, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jQuadroExamesLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(lblOpcaoEx)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tx11, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(161, Short.MAX_VALUE))
        );
        jQuadroExamesLayout.setVerticalGroup(
            jQuadroExamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jQuadroExamesLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(lblTituloEx)
                .addGap(62, 62, 62)
                .addGroup(jQuadroExamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLocalEx)
                    .addComponent(tx8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jQuadroExamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataEx)
                    .addComponent(tx9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jQuadroExamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jQuadroExamesLayout.createSequentialGroup()
                        .addGroup(jQuadroExamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHoraEx)
                            .addComponent(tx10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(jQuadroExamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblOpcaoEx)
                            .addComponent(tx11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(jQuadroExamesLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(B5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jQuadroExames, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jQuadroExames, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5ActionPerformed
        //pegando o que foi digitado no Nome do formulario e atualizando
        //padrão mvc
                            exame.setLocal_exame(tx8.getText());
                            exame.setData_exame(tx9.getText());
                            exame.setHora_exame(tx10.getText());
                            exame.setOpcaoExame(tx11.getText());
                            
                            
                           
                            exameBD = new exameDAO();
                            exameBD.insert(exame);
                            
                            // limpar campos
                            tx8.setText("");
			    tx9.setText("");
                            tx10.setText("");
			    tx11.setText("");    
 
    }//GEN-LAST:event_B5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new UsuarioPerfil().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsuarioExame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsuarioExame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsuarioExame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsuarioExame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsuarioExame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B5;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jQuadroExames;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JLabel lblDataEx;
    private javax.swing.JLabel lblHoraEx;
    private javax.swing.JLabel lblLocalEx;
    private javax.swing.JLabel lblOpcaoEx;
    private javax.swing.JLabel lblTituloEx;
    private javax.swing.JTextField tx10;
    private javax.swing.JTextField tx11;
    private javax.swing.JTextField tx8;
    private javax.swing.JTextField tx9;
    // End of variables declaration//GEN-END:variables
}
