-- MySQL Script generated by MySQL Workbench
-- Tue May 28 20:35:22 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome_usuario` VARCHAR(45) NOT NULL,
  `senha_usuario` VARCHAR(8) NOT NULL,
  `dataDeNascimento` VARCHAR(10) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `tipoSanguineo` VARCHAR(3) NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AgendarDoacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AgendarDoacao` (
  `codigoDoacao` VARCHAR(45) NOT NULL,
  `local_doacao` VARCHAR(45) NOT NULL,
  `data_doacao` VARCHAR(8) NOT NULL,
  `hora_doacao` VARCHAR(5) NOT NULL,
  `opcaoDoacao` VARCHAR(45) NOT NULL,
  `Usuario_id_usuario` INT NOT NULL,
  PRIMARY KEY (`Usuario_id_usuario`, `codigoDoacao`),
  INDEX `fk_AgendarDoacao_Usuario_idx` (`Usuario_id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_AgendarDoacao_Usuario`
    FOREIGN KEY (`Usuario_id_usuario`)
    REFERENCES `mydb`.`Usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AgendarExames`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AgendarExames` (
  `codigoExame` VARCHAR(45) NOT NULL,
  `local_exame` VARCHAR(45) NOT NULL,
  `data_exame` VARCHAR(8) NOT NULL,
  `hora_exame` VARCHAR(5) NOT NULL,
  `OpcaoExame` VARCHAR(45) NOT NULL,
  `Usuario_id_usuario` INT NOT NULL,
  PRIMARY KEY (`Usuario_id_usuario`, `codigoExame`),
  CONSTRAINT `fk_AgendarExames_Usuario1`
    FOREIGN KEY (`Usuario_id_usuario`)
    REFERENCES `mydb`.`Usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
